"""Add notification

Revision ID: 828d2ea066a8
Revises: fcd78a60f7c8
Create Date: 2022-08-14 08:09:49.370722

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "828d2ea066a8"
down_revision = "fcd78a60f7c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
