"""Create wind and precipitation tables

Revision ID: fcd78a60f7c8
Revises: 
Create Date: 2022-01-30 10:30:53.034082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcd78a60f7c8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "precipitation_measurement",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "timestamp"),
    )
    op.create_table(
        "wind_measurement",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("direction", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "timestamp"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wind_measurement")
    op.drop_table("precipitation_measurement")
    # ### end Alembic commands ###
